### ISSUE TITLE
3.0 Validation: cannot select a page in the Pages widget

### ISSUE THREAD

**Issue by elrayle** [cul-it/exhibits-library-cornell-edu#503] opened 2021-08-12 15:09 UTC
2021-07-30 email from Craig Mains...

> The widget that highlights pages from the exhibit doesn’t bring up titles when you type them in and doesn’t allow you to enter titles into Enter a title.. Field. 

To reproduce:

* My test has been in the unpublished site "Bluest Eye". 
* https://exhibits-prod-1.library.cornell.edu/bluest-eye
* I have attempted to add a link button for the feature page "Translations" to the home page.
* Currently the home page has links for Migration, Gender and Sexuality and Beauty, Race & Racism. 
* I click on the blue edit button on the home page and press the plus symbol at the bottom of the page
* I choose the exhibit item widget "pages" to get the box that says "This widget highlights pages from this exhibit. Each highlighted item links to the corresponding page."  
* When I enter the page title, nothing happens. 
* If I hit enter, edit page closes. 
* I try this with the page "Migration" since it is also a viewable page (feature page is checked and shows white check on blue background on feature page index) and an existing working button/link and this too doesn't work.  
* Typing something in the box that says "Enter a Title". should bring up any or all of the existing viewable pages, but nothing populates the box no matter what title I put in the field.
* I'm using Chrome on a remote laptop.

**Comment by elrayle** [comment] 2021-08-12 15:19
I wasn't able to reproduce in my test exhibit.  I did notice that the page had to be visible to be selected.

I need to retest now that the steps to reproduce have been added to the issue.

**Comment by elrayle** [comment] 2022-04-26 21:25
I am not able to reproduce this in my test exhibit or The Bluest Eye exhibits.

Sent email to Craig Mains asking that he retest this issue.  Likely this can be closed.

**Comment by chrisrlc** [comment] 2023-02-20 22:30
Can't reproduce and no updates since last April after reaching out to reporter. Closing out but can reopen if new report comes in.

**Closed** 2023-02-20 22:36 UTC
Labels: bug, Upgrade, immediate
