### ISSUE TITLE
Disable Video widget

### ISSUE THREAD

**Issue by mhk33** [cul-it/exhibits-library-cornell-edu#147] opened 2017-11-28 16:08 UTC
Rachel at Kheel tried to upload via the widget and that caused problems including filling up the /tmp directory. We should encourage people to use Embed + Text or Iframe Embed instead.

**Comment by elrayle** [comment] 2021-01-11 17:35
How to fix a broken page caused by failed video upload:
* ssh to production machine
* login to mysql (see AWS config)
* `use exhibits;`
* get exhibit id -- `select id, slug from spotlight_exhibits;` (referred to as _EXHIBIT_ID_ in remaining examples)
* get page id -- `select id, slug from spotlight_pages where exhibit_id = _EXHIBIT_ID_;` (referred to as _PAGE_ID_ in remaining examples
* get page content -- `select content from spotlight_pages where id=_PAGE_ID_;`
* copy and paste page content into an editor
  * search for video.  In my repair, the video entry looked like...
`       {"type":"video","data":{}},`
  * remove the bad video code from the content in the text editor (deleted the above text from the full content) (referred to as _REPAIRED_CONTENT_ in remaining examples) BE SURE TO INCLUDE THE TRAILING COMMA
  * replace all instances of single quote `'` with escaped single quote `\'` in _REPAIRED_CONTENT_
  * replace all instances of escaped double quote `\"` with double escaped double quote `\\"` in _REPAIRED_CONTENT_
  * copy the _REPAIRED_CONTENT_ to the clipboard
* update the page entry in mysql using -- `update spotlight_pages set content='_REPAIRED_CONTENT_' where id=_PAGE_ID_;`

**Comment by elrayle** [comment] 2021-02-01 15:55
PR #407 reverted the change to remove the video widget.  With the widget disabled, editing a page that previously used this widget to add a video had the video removed.  This is undesirable, so the change was reverted adding the video widget back in.

We need to re-evaluate a plan for removing the video widget.

**Comment by elrayle** [comment] 2021-02-01 16:28
There are 18 pages that include at least 1 video uploaded through the video widget.

```
select id, title, slug from spotlight_pages where content like ('%{\"type\":\"video\",\"data\"%');
```

Looking for how the video was uploaded (e.g. from youtube, from a file on localhost, etc.) to see if there is a pattern to what works and what fails.

**Comment by chrisrlc** [comment] 2023-02-22 16:25
select count(*) from spotlight_pages where content like ('%{\"type\":\"video\",\"data\"%');            
+----------+
| count(*) |
+----------+
|       29 |
+----------+
1 row in set (0.08 sec)

Will need to keep ears open about video upload failures and/or check out current /tmp size. Not sure if this is still an issue though (created in 2017).

**Comment by chrisrlc** [comment] 2023-03-22 20:38
Double checked tmp/ size on prod and checked out existing spotlight pages with video embeds and everything seems to be working. Closing out, but can reopen if new issues reported.

**Closed by chrisrlc** 2023-03-22 20:38 UTC
Labels: short term, cleanup
