### ISSUE TITLE
Indicate which pages an item is included within

### ISSUE THREAD

**Issue by hudajkhan** [cul-it/exhibits-library-cornell-edu#589] opened 2022-12-14 16:51 UTC
**Is your feature request related to a problem? Please describe.**
Request from copyright office: On an individual item view, include way of representing where item is used within the larger exhibit. 

**Describe the solution you'd like**
Under each item, list the pages of the exhibit where that item has been utilized.

**Describe alternatives you've considered**
Breadcrumbs for navigation.  These currently only appear for logged in superadmin roles. 

**Additional context**

**Comment by chrisrlc** [comment] 2023-02-20 19:23
@JesiBuell79 Looks like work was done for this already and deployed to prod. See the "This item was used on the following pages" note at the bottom of: https://exhibits.library.cornell.edu/backyard-revival-american-heritage-poultry/catalog/29-2105. Do we need someone in the copyright office to review and confirm before I can close this out?

**Comment by JesiBuell79** [comment] 2023-02-20 20:56
@chrisrlc - it'd be good to check.  Can you write Amy Dygert and confirm?

**Comment by chrisrlc** [comment] 2023-02-20 21:22
Reached out to Amy. Will update this issue when I hear back.

**Comment by chrisrlc** [comment] 2023-04-03 16:28
Confirmed by Matthew T Kopel from Copyright Office that the current fix in prod is sufficient.

**Closed by chrisrlc** 2023-04-03 16:28 UTC
Labels: enhancement, long term
