### ISSUE TITLE
Unable to edit page title

### ISSUE THREAD

**Issue by mhk33** [cul-it/exhibits-library-cornell-edu#166] opened 2018-06-13 16:17 UTC
Rachel from Costume/Kheel is unable to edit the page title on this page:
https://exhibits.library.cornell.edu/biggest-little-fashion-city/feature/the-biggest-little-fashion-city

She says she gets an error when she tries to save it, though she's able to make other changes on the page without a problem.

I don't get an error when saving it.

**Comment by elrayle** [comment] 2020-11-24 16:32
Closing... Unable to reproduce.

**Closed by elrayle** 2020-11-24 16:32 UTC
Labels: wontfix
