### ISSUE TITLE
"Save this search" on results doesn't seem to work

### ISSUE THREAD

**Issue by mhk33** [cul-it/exhibits-library-cornell-edu#56] opened 2017-03-02 18:44 UTC
To replicate:

- Within an exhibit, do a search.
- Click the "save this search" button on the results and give it a title.
- Go to Saved Searches and the search isn't there.

If you go to Search History, you'll see your search, and you can save it from there, and that seems to work.

**Comment by cappadona** [comment] 2017-04-10 15:22
Possibly related to #64

**Comment by cappadona** [comment] 2017-06-01 16:32
I may be completely off base with this, but I think the *Save Search* feature within Spotlight **does not equal** the *Save Search* feature included in Blacklight core.

It looks like saving a search in Spotlight generates a new Browse Category available to the Exhibit. Including a screenshot from a test I just ran
<img width="954" alt="screenshot 2017-06-01 12 30 18" src="https://cloud.githubusercontent.com/assets/409842/26690167/4fbea178-46c6-11e7-8879-a8bffb9b9593.png">
:

**Comment by starsplatter** [comment] 2017-06-01 16:34
You're right. This is working as intended.

I will not replicate the curse words I generated upon reading this. I think we should close this and make sure the functionality is documented for curators.

**Comment by cappadona** [comment] 2017-06-01 16:36
Agreed. Created #99 to cover documentation.

**Closed by cappadona** 2017-06-01 16:36 UTC
Labels: bug
